### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by dcaffull** [zenparsing/zen-push#3]
Over a year ago, zen-observable was updated to the latest version: https://github.com/zenparsing/zen-push/commit/f54e53c5cb976d0f017bf9d0c602c0410767dc87

However, it doesn't appear that the change was ever released. The latest version, 0.2.1, still has a dependency on zen-observable ^0.7.0 - https://unpkg.com/zen-push@0.2.1/package.json

Please could we get a new release?

**Comment by mlavina** [comment]
@zenparsing Is there any update on this?

**Comment by nupurjain09** [comment]
@zenparsing - Any update? It would be helpful in deduping `zen-observable` dependency in consuming apps if a new release was created for the latest version.

**Comment by zenparsing** [comment]
Will update this soon!

**Comment by zenparsing** [comment]
Done (0.3.0)
